version: "3"
services:
  bangumi-db:
    build: https://github.com/tuihub/bangumi-db.git#master:postgresql
    restart: unless-stopped
    ports:
      - 10000:5432
  vndb-db:
    build: https://github.com/tuihub/vndb-db.git#master
    restart: unless-stopped
    ports:
      - 10001:5432