name: Update game_id_connector

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup docker-compose
      uses: KengoTODA/actions-setup-docker-compose@v1.2.3
      with:
        version: "2.31.0"
    - name: Build and run docker compose containers
      run: |
        cd scripts/vndb_id_connector
        docker compose up -d
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run game_id_merger
      run: |
        cd scripts/game_id_merger
        python main.py
    - name: Stop docker compose containers
      run: |
        cd scripts/vndb_id_connector
        docker compose down

    - name: GitHub Commit & Push
      uses: actions-js/push@v1.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "master"
